# Generated by Django 5.1.5 on 2025-01-20 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_teacher_grades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='grades',
        ),
    ]
