# Generated by Django 5.1.5 on 2025-01-21 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_remove_teacher_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='area',
            field=models.CharField(choices=[('Ingles de kinder a tecero 2', 'Ingles de kinder a tecero 2'), ('Ingles de cuarto a noveno', 'Ingles de cuarto a noveno'), ('Español', 'Español'), ('Matematicas', 'Matematicas ')], max_length=50),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='appointments.grade')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='appointments.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.subject'),
        ),
    ]
