# Generated by Django 5.1.5 on 2025-01-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_email_appointment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='grades',
            field=models.ManyToManyField(related_name='teachers', to='appointments.grade'),
        ),
    ]
