# Generated by Django 5.1.5 on 2025-01-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_relationship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='relationship',
            field=models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Tutor', 'Tutor'), ('Hermano', 'Hermano'), ('Otro', 'Otro')], max_length=50),
        ),
    ]
